// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA17KCdh9_nMt0bx3Di4_JfLP7BFF7MmUE',
    appId: '1:165113025769:web:70826b195b6d6c9659cc78',
    messagingSenderId: '165113025769',
    projectId: 'medmanage-451913',
    authDomain: 'medmanage-451913.firebaseapp.com',
    storageBucket: 'medmanage-451913.firebasestorage.app',
    measurementId: 'G-WYGG88NWQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd2Mbo0QgJrwudKPHAGwbJRQPEI8jPZkA',
    appId: '1:165113025769:android:b10f41cd7af30ef559cc78',
    messagingSenderId: '165113025769',
    projectId: 'medmanage-451913',
    storageBucket: 'medmanage-451913.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Exa75xkIrHiZp2YmWiU7WtUMqS2Vi2s',
    appId: '1:165113025769:ios:67b072e9002f152d59cc78',
    messagingSenderId: '165113025769',
    projectId: 'medmanage-451913',
    storageBucket: 'medmanage-451913.firebasestorage.app',
    iosBundleId: 'com.example.medmanage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3Exa75xkIrHiZp2YmWiU7WtUMqS2Vi2s',
    appId: '1:165113025769:ios:67b072e9002f152d59cc78',
    messagingSenderId: '165113025769',
    projectId: 'medmanage-451913',
    storageBucket: 'medmanage-451913.firebasestorage.app',
    iosBundleId: 'com.example.medmanage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA17KCdh9_nMt0bx3Di4_JfLP7BFF7MmUE',
    appId: '1:165113025769:web:565921fed3277e4559cc78',
    messagingSenderId: '165113025769',
    projectId: 'medmanage-451913',
    authDomain: 'medmanage-451913.firebaseapp.com',
    storageBucket: 'medmanage-451913.firebasestorage.app',
    measurementId: 'G-Z2BFCDQGM1',
  );
}
